import csv
import re

datamine_pkm_to_pcw = {
    "venusaur-1": "venusaurM",
    "charizard-1": "charizardMX",
    "charizard-2": "charizardMY",
    "blastoise-1": "blastoiseM",
    "beedrill-1": "beedrillM",
    "pidgeot-1": "pidgeotM",
    "clefable-1": "clefableM",
    "alakazam-1": "alakazamM",
    "victreebel-1": "victreebelM",
    "slowbro-1": "slowbroM",
    "gengar-1": "gengarM",
    "kangaskhan-1": "kangaskhanM",
    "starmie-1": "starmieM",
    "pinsir-1": "pinsirM",
    "gyarados-1": "gyaradosM",
    "aerodactyl-1": "aerodactylM",
    "dragonite-1": "dragoniteM",
    "mewtwo-1": "mewtwoMX",
    "mewtwo-2": "mewtwoMY",
    "meganium-1": "meganiumM",
    "feraligatr-1": "feraligatrM",
    "ampharos-1": "ampharosM",
    "steelix-1": "steelixM",
    "scizor-1": "scizorM",
    "heracross-1": "heracrossM",
    "skarmory-1": "skarmoryM",
    "houndoom-1": "houndoomM",
    "tyranitar-1": "tyranitarM",
    "gardevoir-1": "gardevoirM",
    "sableye-1": "sableyeM",
    "mawile-1": "mawileM",
    "aggron-1": "aggronM",
    "medicham-1": "medichamM",
    "manectric-1": "manectricM",
    "sharpedo-1": "sharpedoM",
    "camerupt-1": "cameruptM",
    "altaria-1": "altariaM",
    "banette-1": "banetteM",
    "absol-1": "absolM",
    "glalie-1": "glalieM",
    "salamence-1": "salamenceM",
    "metagross-1": "metagrossM",
    "lopunny-1": "lopunnyM",
    "garchomp-1": "garchompM",
    "lucario-1": "lucarioM",
    "abomasnow-1": "abomasnowM",
    "gallade-1": "galladeM",
    "froslass-1": "froslassM",
    "emboar-1": "emboarM",
    "excadrill-1": "excadrillM",
    "audino-1": "audinoM",
    "scolipede-1": "scolipedeM",
    "scrafty-1": "scraftyM",
    "eelektross-1": "eelektrossM",
    "chandelure-1": "chandelureM",
    "chesnaught-1": "chesnaughtM",
    "delphox-1": "delphoxM",
    "greninja-3": "greninjaM",
    "pyroar-1": "pyroarM",
    "floette-5": "floetteE",
    "floette-6": "floetteM",
    "malamar-1": "malamarM",
    "barbaracle-1": "barbaracleM",
    "dragalge-1": "dragalgeM",
    "hawlucha-1": "hawluchaM",
    "diancie-1": "diancieM",
    "drampa-1": "drampaM",
    "falinks-1": "falinksM",
    "mr.-mime": "mr. mime",
    "mr.-mime-1": "mr. mimeG",
    "mime-jr.": "mime jr.",
    "mr.-rime": "mr. rime",
    "pikachu": "pikachu",
    "pikachu-1": "pikachuO",
    "pikachu-2": "pikachuH",
    "pikachu-3": "pikachuSi",
    "pikachu-4": "pikachuU",
    "pikachu-5": "pikachuK",
    "pikachu-6": "pikachuA",
    "pikachu-7": "pikachuCo",
    "raichu": "raichu",
    "raichu-1": "raichuA",
    "darumaka": "darumaka",
    "darumaka-1": "darumakaG",
    "darmanitan": "darmanitan",
    "darmanitan-1": "darmanitanZ",
    "darmanitan-2": "darmanitanG",
    "darmanitan-3": "darmanitanGZ",
    "vulpix": "vulpix",
    "vulpix-1": "vulpixA",
    "ninetales": "ninetales",
    "ninetales-1": "ninetalesA",
    "diglett": "diglett",
    "diglett-1": "diglettA",
    "dugtrio": "dugtrio",
    "dugtrio-1": "dugtrioA",
    "meowth": "meowth",
    "meowth-1": "meowthA",
    "meowth-2": "meowthG",
    "persian": "persian",
    "persian-1": "persianA",
    "ponyta": "ponyta",
    "ponyta-1": "ponytaG",
    "rapidash": "rapidash",
    "rapidash-1": "rapidashG",
    "weezing": "weezing",
    "weezing-1": "weezingG",
    "corsola": "corsola",
    "corsola-1": "corsolaG",
    "zigzagoon": "zigzagoon",
    "zigzagoon-1": "zigzagoonG",
    "linoone": "linoone",
    "linoone-1": "linooneG",
    "stunfisk": "stunfisk",
    "stunfisk-1": "stunfiskG",
    "farfetch'd": "farfetchd",
    "farfetch’d": "farfetchd",
    "farfetch'd-1": "farfetchdG",
    "farfetch’d-1": "farfetchdG",
    "sirfetch'd": "sirfetchd",
    "sirfetch’d": "sirfetchd",
    "cramorant": "cramorant",
    "cramorant-1": "cramorantT",
    "cramorant-2": "cramorantI",
    "toxtricity": "toxtricity",
    "toxtricity-1": "toxtricityB",
    "eiscue": "eiscue",
    "eiscue-1": "eiscueL",
    "indeedee": "indeedee",
    "indeedee-1": "indeedeeF",
    "morpeko": "morpeko",
    "morpeko-1": "morpekoV",
    "zacian": "zacian",
    "zacian-1": "zacianR",
    "zamazenta": "zamazenta",
    "zamazenta-1": "zamazentaR",
    "eternatus": "eternatus",
    "eternatus-1": "eternatusD",
    "shellos": "shellos",
    "shellos-1": "shellosE",
    "gastrodon": "gastrodon",
    "gastrodon-1": "gastrodonE",
    "cherrim": "cherrim",
    "cherrim-1": "cherrimS",
    "sinistea": "sinistea",
    "sinistea-1": "sinisteaA",
    "polteageist": "polteageist",
    "polteageist-1": "polteageistA",
    "alcremie": "alcremie",
    "alcremie-1": "alcremieR",
    "alcremie-2": "alcremieMa",
    "alcremie-3": "alcremieMe",
    "alcremie-4": "alcremieL",
    "alcremie-5": "alcremieS",
    "alcremie-6": "alcremieRm",
    "alcremie-7": "alcremieCm",
    "alcremie-8": "alcremieTm",
    "mimikyu": "mimikyu",
    "mimikyu-1": "mimikyuS",
    "silvally": "silvally",
    "silvally-1": "silvally",
    "silvally-2": "silvally",
    "silvally-3": "silvally",
    "silvally-4": "silvally",
    "silvally-5": "silvally",
    "silvally-6": "silvally",
    "silvally-7": "silvally",
    "silvally-8": "silvally",
    "silvally-9": "silvally",
    "silvally-10": "silvally",
    "silvally-11": "silvally",
    "silvally-12": "silvally",
    "silvally-13": "silvally",
    "silvally-14": "silvally",
    "silvally-15": "silvally",
    "silvally-16": "silvally",
    "silvally-17": "silvally",
    "type:null": "tipo zero",
    "type:-null": "tipo zero",
    "necrozma": "necrozma",
    "necrozma-1": "necrozmaV",
    "necrozma-2": "necrozmaA",
    "wishiwashi": "wishiwashi",
    "wishiwashi-1": "wishiwashiB",
    "pumpkaboo": "pumpkaboo",
    "pumpkaboo-1": "pumpkabooS",
    "pumpkaboo-2": "pumpkabooL",
    "pumpkaboo-3": "pumpkabooXL",
    "gourgeist": "gourgeist",
    "gourgeist-1": "gourgeistS",
    "gourgeist-2": "gourgeistL",
    "gourgeist-3": "gourgeistXL",
    "aegislash": "aegislash",
    "aegislash-1": "aegislashS",
    "meowstic": "meowstic",
    "meowstic-1": "meowsticF",
    "keldeo": "keldeo",
    "keldeo-1": "keldeoR",
    "kyurem": "kyurem",
    "kyurem-1": "kyuremN",
    "kyurem-2": "kyuremB",
    "yamask": "yamask",
    "yamask-1": "yamaskG",
    "basculin": "basculin",
    "basculin-1": "basculinB",
    "rotom": "rotom",
    "rotom-1": "rotomC",
    "rotom-2": "rotomL",
    "rotom-3": "rotomG",
    "rotom-4": "rotomV",
    "rotom-5": "rotomT",
    "exeggutor-1": "exeggutorA",
    "marowak-1": "marowakA",
    "sandshrew-1": "sandshrewA",
    "sandslash-1": "sandslashA",
    "slowpoke-1": "slowpokeG",
    "slowbro-2": "slowbroG",
    "slowking-1": "slowkingG",
    "lycanroc": "lycanroc",
    "lycanroc-1": "lycanrocN",
    "lycanroc-2": "lycanrocC",
    "urshifu-1": "urshifuP",
    "articuno-1": "articunoG",
    "zapdos-1": "zapdosG",
    "moltres-1": "moltresG",
    "calyrex-1": "calyrexG",
    "calyrex-2": "calyrexS",
    "giratina-1": "giratinaO",
    "tornadus-1": "tornadusT",
    "thundurus-1": "thundurusT",
    "landorus-1": "landorusT",
    "zygarde-1": "zygardeD",
    "zygarde-4": "zygardeP",
    "zygarde-5": "zygardeM",
    "tapu-koko": "tapu koko",
    "tapu-lele": "tapu lele",
    "tapu-bulu": "tapu bulu",
    "tapu-fini": "tapu fini",
    "zarude-1": "zarudeP",
    "growlithe-1": "growlitheH",
    "arcanine-1": "arcanineH",
    "grimer-1": "grimerA",
    "muk-1": "mukA",
    "voltorb-1": "voltorbH",
    "electrode-1": "electrodeH",
    "typhlosion-1": "typhlosionH",
    "samurott-1": "samurottH",
    "decidueye-1": "decidueyeH",
    "qwilfish-1": "qwilfishH",
    "sneasel-1": "sneaselH",
    "dialga-1": "dialgaO",
    "palkia-1": "palkiaO",
    "lilligant-1": "lilligantH",
    "basculin-2": "basculinBi",
    "zorua-1": "zoruaH",
    "zoroark-1": "zoroarkH",
    "braviary-1": "braviaryH",
    "sliggoo-1": "sliggooH",
    "goodra-1": "goodraH",
    "avalugg-1": "avaluggH",
    "meloetta-1": "meloettaD",
    # "greninja-1": "greninjaA",
    "hoopa-1": "hoopaL",
    "oricorio-1": "oricorioC",
    "oricorio-2": "oricorioH",
    "oricorio-3": "oricorioB",
    "basculegion-1": "basculegionF",
    "enamorus-1": "enamorusT",
    "gimmighoul-1": "gimmighoulA",
    "tauros-1": "taurosC",
    "tauros-2": "taurosI",
    "tauros-3": "taurosA",
    "wooper-1": "wooperP",
    "oinkologne-1": "oinkologneF",
    "palafin-1": "palafinP",
    "maushold-1": "mausholdQ",
    "squawkabilly-1": "squawkabillyA",
    "squawkabilly-2": "squawkabillyG",
    "squawkabilly-3": "squawkabillyB",
    "geodude-1": "geodudeA",
    "graveler-1": "gravelerA",
    "golem-1": "golemA",
    "shaymin-1": "shayminC",
    "ursaluna-1": "ursalunaL",
    "ogerpon-1": "ogerponP",
    "ogerpon-2": "ogerponFc",
    "ogerpon-3": "ogerponFn",
    # Paradox
    "great-tusk": "grandizanne",
    "brute-bonnet": "fungofurioso",
    "sandy-shocks": "peldisabbia",
    "scream-tail": "codaurlante",
    "flutter-mane": "crinealato",
    "slither-wing": "alirasenti",
    "roaring-moon": "lunaruggente",
    "iron-treads": "solcoferreo",
    "iron-moth": "falenaferrea",
    "iron-hands": "manoferrea",
    "iron-jugulis": "colloferreo",
    "iron-thorns": "spineferree",
    "iron-bundle": "saccoferreo",
    "iron-valiant": "eroeferreo",
    "walking-wake": "acquecrespe",
    "iron-leaves": "fogliaferrea",
    "gouging-fire": "vampeaguzze",
    "raging-bolt": "furiatonante",
    "iron-crown": "capoferreo",
    "iron-boulder": "massoferreo",
    # End paradox
    "deoxys-1": "deoxysA",
    "deoxys-2": "deoxysD",
    "deoxys-3": "deoxysV",
    "minior-7": "miniorR",
}

ignores = list(
    map(
        re.compile,
        [
            "pikachu(O|H|Si|U|K|A|Co|G|-9)",
            "shellosE",
            "gastrodonE",
            r"arceus-\d{1,2}",
            "deerling-[1-3]",
            "sawsbuck-[1-3]",
            "greninja-1",
            r"scatterbug-\d{1,2}",
            r"spewpa-\d{1,2}",
            r"vivillon-\d{1,2}",
            "flabébé-[1-4]",
            "floette-[1-4]",
            "florges-[1-4]",
            "furfrou-[1-9]",
            "zygarde-[2-3]",
            "magearna-1",
            "dudunsparce-1",
            "mausholdQ",
            "tatsugiri-[12]",
            "koraidon-[1-4]",
            "miraidon-[1-4]",
            "rockruff-1",
            "poltchageist-1",
            "sinistcha-1",
            "ogerpon-[4-7]",
            "minior-(1|2|3|4|5|6|8|9|10|11|12|13|14)",
            "alcremie(R|Ma|Me|L|S|Rm|Cm|Tm)",
            "terapagos-(1|2)",
        ],
    )
)

IS_VALID_IDENTIFIER = re.compile(r"[_\w][_\w\d]*")


def convert_pokename(poke: str):
    poke = poke.lower().replace(" ", "-")
    if poke in datamine_pkm_to_pcw:
        return datamine_pkm_to_pcw[poke]
    else:
        return poke


def find(items, predicate):
    return next(i for i in items if predicate(i))


def get_move_id(move: str):
    move = move.strip().lower()
    # 1,botta,1,1,40,35,100,0,10,2,1,,5,1,5
    with open("docker-db/sourcecsv/moves.csv", "r") as movesfile:
        moves = csv.reader(movesfile)
        next(moves)
        for line in moves:
            if line[1].strip().lower() == move:
                return line[0]


def get_poke_id(poke: str):
    poke = poke.strip().lower()
    # 1,botta,1,1,40,35,100,0,10,2,1,,5,1,5
    with open("docker-db/sourcecsv/pokemon.csv", "r") as file:
        r = csv.reader(file)
        next(r)
        for line in r:
            if line[1].strip().lower() == poke:
                return line[0]


def sanitize_lua_table_key(key: str) -> str:
    return f".{key}" if IS_VALID_IDENTIFIER.fullmatch(key) else f'["{key}"]'


def should_ignore(pokename: str):
    return any(map(lambda p: re.fullmatch(p, pokename), ignores))
