import re

replaces = {
    "mr.-mime": "mr. mime",
    "mr.-mime-1": "mr. mimeG",
    "mime-jr.": "mime jr.",
    "mr.-rime": "mr. rime",
    "pikachu": "pikachu",
    "pikachu-1": "pikachuO",
    "pikachu-2": "pikachuH",
    "pikachu-3": "pikachuSi",
    "pikachu-4": "pikachuU",
    "pikachu-5": "pikachuK",
    "pikachu-6": "pikachuA",
    "pikachu-7": "pikachuCo",
    "raichu": "raichu",
    "raichu-1": "raichuA",
    "darumaka": "darumaka",
    "darumaka-1": "darumakaG",
    "darmanitan": "darmanitan",
    "darmanitan-1": "darmanitanZ",
    "darmanitan-2": "darmanitanG",
    "darmanitan-3": "darmanitanGZ",
    "vulpix": "vulpix",
    "vulpix-1": "vulpixA",
    "ninetales": "ninetales",
    "ninetales-1": "ninetalesA",
    "diglett": "diglett",
    "diglett-1": "diglettA",
    "dugtrio": "dugtrio",
    "dugtrio-1": "dugtrioA",
    "meowth": "meowth",
    "meowth-1": "meowthA",
    "meowth-2": "meowthG",
    "persian": "persian",
    "persian-1": "persianA",
    "ponyta": "ponyta",
    "ponyta-1": "ponytaG",
    "rapidash": "rapidash",
    "rapidash-1": "rapidashG",
    "weezing": "weezing",
    "weezing-1": "weezingG",
    "corsola": "corsola",
    "corsola-1": "corsolaG",
    "zigzagoon": "zigzagoon",
    "zigzagoon-1": "zigzagoonG",
    "linoone": "linoone",
    "linoone-1": "linooneG",
    "stunfisk": "stunfisk",
    "stunfisk-1": "stunfiskG",
    "farfetch'd": "farfetchd",
    "farfetch’d": "farfetchd",
    "farfetch'd-1": "farfetchdG",
    "farfetch’d-1": "farfetchdG",
    "sirfetch'd": "sirfetchd",
    "sirfetch’d": "sirfetchd",
    "cramorant": "cramorant",
    "cramorant-1": "cramorantT",
    "cramorant-2": "cramorantI",
    "toxtricity": "toxtricity",
    "toxtricity-1": "toxtricityB",
    "eiscue": "eiscue",
    "eiscue-1": "eiscueL",
    "indeedee": "indeedee",
    "indeedee-1": "indeedeeF",
    "morpeko": "morpeko",
    "morpeko-1": "morpekoV",
    "zacian": "zacian",
    "zacian-1": "zacianR",
    "zamazenta": "zamazenta",
    "zamazenta-1": "zamazentaR",
    "eternatus": "eternatus",
    "eternatus-1": "eternatusD",
    "shellos": "shellos",
    "shellos-1": "shellosE",
    "gastrodon": "gastrodon",
    "gastrodon-1": "gastrodonE",
    "cherrim": "cherrim",
    "cherrim-1": "cherrimS",
    "sinistea": "sinistea",
    "sinistea-1": "sinisteaA",
    "polteageist": "polteageist",
    "polteageist-1": "polteageistA",
    "alcremie": "alcremie",
    "alcremie-1": "alcremieR",
    "alcremie-2": "alcremieMa",
    "alcremie-3": "alcremieMe",
    "alcremie-4": "alcremieL",
    "alcremie-5": "alcremieS",
    "alcremie-6": "alcremieRm",
    "alcremie-7": "alcremieCm",
    "alcremie-8": "alcremieTm",
    "mimikyu": "mimikyu",
    "mimikyu-1": "mimikyuS",
    "silvally": "silvally",
    "silvally-1": "silvally",
    "silvally-2": "silvally",
    "silvally-3": "silvally",
    "silvally-4": "silvally",
    "silvally-5": "silvally",
    "silvally-6": "silvally",
    "silvally-7": "silvally",
    "silvally-8": "silvally",
    "silvally-9": "silvally",
    "silvally-10": "silvally",
    "silvally-11": "silvally",
    "silvally-12": "silvally",
    "silvally-13": "silvally",
    "silvally-14": "silvally",
    "silvally-15": "silvally",
    "silvally-16": "silvally",
    "silvally-17": "silvally",
    "type:null": "tipo zero",
    "type:-null": "tipo zero",
    "necrozma": "necrozma",
    "necrozma-1": "necrozmaV",
    "necrozma-2": "necrozmaA",
    "wishiwashi": "wishiwashi",
    "wishiwashi-1": "wishiwashiB",
    "pumpkaboo": "pumpkaboo",
    "pumpkaboo-1": "pumpkabooS",
    "pumpkaboo-2": "pumpkabooL",
    "pumpkaboo-3": "pumpkabooXL",
    "gourgeist": "gourgeist",
    "gourgeist-1": "gourgeistS",
    "gourgeist-2": "gourgeistL",
    "gourgeist-3": "gourgeistXL",
    "aegislash": "aegislash",
    "aegislash-1": "aegislashS",
    "meowstic": "meowstic",
    "meowstic-1": "meowsticF",
    "keldeo": "keldeo",
    "keldeo-1": "keldeoR",
    "kyurem": "kyurem",
    "kyurem-1": "kyuremN",
    "kyurem-2": "kyuremB",
    "yamask": "yamask",
    "yamask-1": "yamaskG",
    "basculin": "basculin",
    "basculin-1": "basculinB",
    "rotom": "rotom",
    "rotom-1": "rotomC",
    "rotom-2": "rotomL",
    "rotom-3": "rotomG",
    "rotom-4": "rotomV",
    "rotom-5": "rotomT",
    "exeggutor-1": "exeggutorA",
    "marowak-1": "marowakA",
    "sandshrew-1": "sandshrewA",
    "sandslash-1": "sandslashA",
    "slowpoke-1": "slowpokeG",
    "slowbro-2": "slowbroG",
    "slowking-1": "slowkingG",
    "lycanroc": "lycanroc",
    "lycanroc-1": "lycanrocN",
    "lycanroc-2": "lycanrocC",
    "urshifu-1": "urshifuP",
    "articuno-1": "articunoG",
    "zapdos-1": "zapdosG",
    "moltres-1": "moltresG",
    "calyrex-1": "calyrexG",
    "calyrex-2": "calyrexS",
    "giratina-1": "giratinaO",
    "tornadus-1": "tornadusT",
    "thundurus-1": "thundurusT",
    "landorus-1": "landorusT",
    "zygarde-1": "zygardeD",
    "zygarde-4": "zygardeP",
    "tapu-koko": "tapu koko",
    "tapu-lele": "tapu lele",
    "tapu-bulu": "tapu bulu",
    "tapu-fini": "tapu fini",
    "zarude-1": "zarudeP",
    "growlithe-1": "growlitheH",
    "arcanine-1": "arcanineH",
    "grimer-1": "grimerA",
    "muk-1": "mukA",
    "voltorb-1": "voltorbH",
    "electrode-1": "electrodeH",
    "tauros-1": "taurosPa",
    "tauros-2": "taurosPb",
    "tauros-3": "taurosPc",
    "typhlosion-1": "typhlosionH",
    "samurott-1": "samurottH",
    "decidueye-1": "decidueyeH",
    "wooper-1": "wooperP",
    "qwilfish-1": "qwilfishH",
    "sneasel-1": "sneaselH",
    "dialga-1": "dialgaO",
    "palkia-1": "palkiaO",
    "lilligant-1": "lilligantH",
    "basculin-2": "basculinBi",
    "zorua-1": "zoruaH",
    "zoroark-1": "zoroarkH",
    "braviary-1": "braviaryH",
    "sliggoo-1": "sliggooH",
    "goodra-1": "goodraH",
    "avalugg-1": "avaluggH",
    "meloetta-1": "meloettaD",
    "greninja-1": "greninjaA",
    "hoopa-1": "hoopaL",
    "oricorio-1": "oricorioC",
    "oricorio-2": "oricorioH",
    "oricorio-3": "oricorioB",
    "basculegion-1": "basculegionF",
    "enamorus-1": "enamorusT",
    "gimmighoul-1": "gimmighoulA",
    # TODO
    "oinkologne-1": "oinkologneF",
    "palafin-1": "palafin-1",
    "maushold-1": "maushold-1",
    "tatsugiri-1": "tatsugiri-1",
    "tatsugiri-2": "tatsugiri-2",
    "squawkabilly-1": "squawkabilly-1",
    "squawkabilly-2": "squawkabilly-2",
    "squawkabilly-3": "squawkabilly-3",
    "great-tusk": "grandizanne",
    "iron-treads": "solcoferreo",
}

ignores = list(
    map(
        re.compile,
        [
            "pikachu(O|H|Si|U|K|A|Co|G)",
            "shellosE",
            "gastrodonE",
            "arceus-\d{1,2}",
            "deerling-\d",
            "sawsbuck-\d",
            "scatterbug-\d{1,2}",
            "spewpa-\d{1,2}",
            "vivillon-\d{1,2}",
            "flabébé-\d",
            "floette-\d",
            "florges-\d",
            "magearna-1",
            # TODO
            "dudunsparce-1",
            "koraidon-\d",
            "miraidon-\d",
        ],
    )
)


def should_ignore(pokename: str):
    return any(map(lambda p: re.fullmatch(p, pokename), ignores))
