--[[

Data module for presence in gen 8 games.

Since not all Pokémon exist in SpSc and DLPS (gen 8 games), this module
contains for each Pokémon a table saying in which games it exists.

--]]

local p = {}

p.bulbasaur = { "SpSc", "DLPS" }
p.ivysaur = { "SpSc", "DLPS" }
p.venusaur = { "SpSc", "DLPS" }
p.charmander = { "SpSc", "DLPS" }
p.charmeleon = { "SpSc", "DLPS" }
p.charizard = { "SpSc", "DLPS" }
p.squirtle = { "SpSc", "DLPS" }
p.wartortle = { "SpSc", "DLPS" }
p.blastoise = { "SpSc", "DLPS" }
p.caterpie = { "SpSc", "DLPS" }
p.metapod = { "SpSc", "DLPS" }
p.butterfree = { "SpSc", "DLPS" }
p.weedle = { "DLPS" }
p.kakuna = { "DLPS" }
p.beedrill = { "DLPS" }
p.pidgey = { "DLPS" }
p.pidgeotto = { "DLPS" }
p.pidgeot = { "DLPS" }
p.rattata = { "DLPS" }
p.raticate = { "DLPS" }
p.spearow = { "DLPS" }
p.fearow = { "DLPS" }
p.ekans = { "DLPS" }
p.arbok = { "DLPS" }
p.pikachu = { "SpSc", "DLPS" }
p.raichu = { "SpSc", "DLPS" }
p.sandshrew = { "SpSc", "DLPS" }
p.sandslash = { "SpSc", "DLPS" }
p["nidoran♀"] = { "SpSc", "DLPS" }
p.nidorina = { "SpSc", "DLPS" }
p.nidoqueen = { "SpSc", "DLPS" }
p["nidoran♂"] = { "SpSc", "DLPS" }
p.nidorino = { "SpSc", "DLPS" }
p.nidoking = { "SpSc", "DLPS" }
p.clefairy = { "SpSc", "DLPS" }
p.clefable = { "SpSc", "DLPS" }
p.vulpix = { "SpSc", "DLPS" }
p.ninetales = { "SpSc", "DLPS" }
p.jigglypuff = { "SpSc", "DLPS" }
p.wigglytuff = { "SpSc", "DLPS" }
p.zubat = { "SpSc", "DLPS" }
p.golbat = { "SpSc", "DLPS" }
p.oddish = { "SpSc", "DLPS" }
p.gloom = { "SpSc", "DLPS" }
p.vileplume = { "SpSc", "DLPS" }
p.paras = { "DLPS" }
p.parasect = { "DLPS" }
p.venonat = { "DLPS" }
p.venomoth = { "DLPS" }
p.diglett = { "SpSc", "DLPS" }
p.dugtrio = { "SpSc", "DLPS" }
p.meowth = { "SpSc", "DLPS" }
p.persian = { "SpSc", "DLPS" }
p.psyduck = { "SpSc", "DLPS" }
p.golduck = { "SpSc", "DLPS" }
p.mankey = { "DLPS" }
p.primeape = { "DLPS" }
p.growlithe = { "SpSc", "DLPS" }
p.arcanine = { "SpSc", "DLPS" }
p.poliwag = { "SpSc", "DLPS" }
p.poliwhirl = { "SpSc", "DLPS" }
p.poliwrath = { "SpSc", "DLPS" }
p.abra = { "SpSc", "DLPS" }
p.kadabra = { "SpSc", "DLPS" }
p.alakazam = { "SpSc", "DLPS" }
p.machop = { "SpSc", "DLPS" }
p.machoke = { "SpSc", "DLPS" }
p.machamp = { "SpSc", "DLPS" }
p.bellsprout = { "DLPS" }
p.weepinbell = { "DLPS" }
p.victreebel = { "DLPS" }
p.tentacool = { "SpSc", "DLPS" }
p.tentacruel = { "SpSc", "DLPS" }
p.geodude = { "DLPS" }
p.graveler = { "DLPS" }
p.golem = { "DLPS" }
p.ponyta = { "SpSc", "DLPS" }
p.rapidash = { "SpSc", "DLPS" }
p.slowpoke = { "SpSc", "DLPS" }
p.slowbro = { "SpSc", "DLPS" }
p.magnemite = { "SpSc", "DLPS" }
p.magneton = { "SpSc", "DLPS" }
p["farfetch'd"] = { "SpSc", "DLPS" }
p.doduo = { "DLPS" }
p.dodrio = { "DLPS" }
p.seel = { "DLPS" }
p.dewgong = { "DLPS" }
p.grimer = { "DLPS" }
p.muk = { "DLPS" }
p.shellder = { "SpSc", "DLPS" }
p.cloyster = { "SpSc", "DLPS" }
p.gastly = { "SpSc", "DLPS" }
p.haunter = { "SpSc", "DLPS" }
p.gengar = { "SpSc", "DLPS" }
p.onix = { "SpSc", "DLPS" }
p.drowzee = { "DLPS" }
p.hypno = { "DLPS" }
p.krabby = { "SpSc", "DLPS" }
p.kingler = { "SpSc", "DLPS" }
p.voltorb = { "DLPS" }
p.electrode = { "DLPS" }
p.exeggcute = { "SpSc", "DLPS" }
p.exeggutor = { "SpSc", "DLPS" }
p.cubone = { "SpSc", "DLPS" }
p.marowak = { "SpSc", "DLPS" }
p.hitmonlee = { "SpSc", "DLPS" }
p.hitmonchan = { "SpSc", "DLPS" }
p.lickitung = { "SpSc", "DLPS" }
p.koffing = { "SpSc", "DLPS" }
p.weezing = { "SpSc", "DLPS" }
p.rhyhorn = { "SpSc", "DLPS" }
p.rhydon = { "SpSc", "DLPS" }
p.chansey = { "SpSc", "DLPS" }
p.tangela = { "SpSc", "DLPS" }
p.kangaskhan = { "SpSc", "DLPS" }
p.horsea = { "SpSc", "DLPS" }
p.seadra = { "SpSc", "DLPS" }
p.goldeen = { "SpSc", "DLPS" }
p.seaking = { "SpSc", "DLPS" }
p.staryu = { "SpSc", "DLPS" }
p.starmie = { "SpSc", "DLPS" }
p["mr. mime"] = { "SpSc", "DLPS" }
p.scyther = { "SpSc", "DLPS" }
p.jynx = { "SpSc", "DLPS" }
p.electabuzz = { "SpSc", "DLPS" }
p.magmar = { "SpSc", "DLPS" }
p.pinsir = { "SpSc", "DLPS" }
p.tauros = { "SpSc", "DLPS" }
p.magikarp = { "SpSc", "DLPS" }
p.gyarados = { "SpSc", "DLPS" }
p.lapras = { "SpSc", "DLPS" }
p.ditto = { "SpSc", "DLPS" }
p.eevee = { "SpSc", "DLPS" }
p.vaporeon = { "SpSc", "DLPS" }
p.jolteon = { "SpSc", "DLPS" }
p.flareon = { "SpSc", "DLPS" }
p.porygon = { "SpSc", "DLPS" }
p.omanyte = { "SpSc", "DLPS" }
p.omastar = { "SpSc", "DLPS" }
p.kabuto = { "SpSc", "DLPS" }
p.kabutops = { "SpSc", "DLPS" }
p.aerodactyl = { "SpSc", "DLPS" }
p.snorlax = { "SpSc", "DLPS" }
p.articuno = { "SpSc", "DLPS" }
p.zapdos = { "SpSc", "DLPS" }
p.moltres = { "SpSc", "DLPS" }
p.dratini = { "SpSc", "DLPS" }
p.dragonair = { "SpSc", "DLPS" }
p.dragonite = { "SpSc", "DLPS" }
p.mewtwo = { "SpSc", "DLPS" }
p.mew = { "SpSc", "DLPS" }
p.chikorita = { "DLPS" }
p.bayleef = { "DLPS" }
p.meganium = { "DLPS" }
p.cyndaquil = { "DLPS" }
p.quilava = { "DLPS" }
p.typhlosion = { "DLPS" }
p.totodile = { "DLPS" }
p.croconaw = { "DLPS" }
p.feraligatr = { "DLPS" }
p.sentret = { "DLPS" }
p.furret = { "DLPS" }
p.hoothoot = { "SpSc", "DLPS" }
p.noctowl = { "SpSc", "DLPS" }
p.ledyba = { "DLPS" }
p.ledian = { "DLPS" }
p.spinarak = { "DLPS" }
p.ariados = { "DLPS" }
p.crobat = { "SpSc", "DLPS" }
p.chinchou = { "SpSc", "DLPS" }
p.lanturn = { "SpSc", "DLPS" }
p.pichu = { "SpSc", "DLPS" }
p.cleffa = { "SpSc", "DLPS" }
p.igglybuff = { "SpSc", "DLPS" }
p.togepi = { "SpSc", "DLPS" }
p.togetic = { "SpSc", "DLPS" }
p.natu = { "SpSc", "DLPS" }
p.xatu = { "SpSc", "DLPS" }
p.mareep = { "DLPS" }
p.flaaffy = { "DLPS" }
p.ampharos = { "DLPS" }
p.bellossom = { "SpSc", "DLPS" }
p.marill = { "SpSc", "DLPS" }
p.azumarill = { "SpSc", "DLPS" }
p.sudowoodo = { "SpSc", "DLPS" }
p.politoed = { "SpSc", "DLPS" }
p.hoppip = { "DLPS" }
p.skiploom = { "DLPS" }
p.jumpluff = { "DLPS" }
p.aipom = { "DLPS" }
p.sunkern = { "DLPS" }
p.sunflora = { "DLPS" }
p.yanma = { "DLPS" }
p.wooper = { "SpSc", "DLPS" }
p.quagsire = { "SpSc", "DLPS" }
p.espeon = { "SpSc", "DLPS" }
p.umbreon = { "SpSc", "DLPS" }
p.murkrow = { "DLPS" }
p.slowking = { "SpSc", "DLPS" }
p.misdreavus = { "DLPS" }
p.unown = { "DLPS" }
p.wobbuffet = { "SpSc", "DLPS" }
p.girafarig = { "DLPS" }
p.pineco = { "DLPS" }
p.forretress = { "DLPS" }
p.dunsparce = { "SpSc", "DLPS" }
p.gligar = { "DLPS" }
p.steelix = { "SpSc", "DLPS" }
p.snubbull = { "DLPS" }
p.granbull = { "DLPS" }
p.qwilfish = { "SpSc", "DLPS" }
p.scizor = { "SpSc", "DLPS" }
p.shuckle = { "SpSc", "DLPS" }
p.heracross = { "SpSc", "DLPS" }
p.sneasel = { "SpSc", "DLPS" }
p.teddiursa = { "DLPS" }
p.ursaring = { "DLPS" }
p.slugma = { "DLPS" }
p.magcargo = { "DLPS" }
p.swinub = { "SpSc", "DLPS" }
p.piloswine = { "SpSc", "DLPS" }
p.corsola = { "SpSc", "DLPS" }
p.remoraid = { "SpSc", "DLPS" }
p.octillery = { "SpSc", "DLPS" }
p.delibird = { "SpSc", "DLPS" }
p.mantine = { "SpSc", "DLPS" }
p.skarmory = { "SpSc", "DLPS" }
p.houndour = { "DLPS" }
p.houndoom = { "DLPS" }
p.kingdra = { "SpSc", "DLPS" }
p.phanpy = { "DLPS" }
p.donphan = { "DLPS" }
p.porygon2 = { "SpSc", "DLPS" }
p.stantler = { "DLPS" }
p.smeargle = { "DLPS" }
p.tyrogue = { "SpSc", "DLPS" }
p.hitmontop = { "SpSc", "DLPS" }
p.smoochum = { "SpSc", "DLPS" }
p.elekid = { "SpSc", "DLPS" }
p.magby = { "SpSc", "DLPS" }
p.miltank = { "SpSc", "DLPS" }
p.blissey = { "SpSc", "DLPS" }
p.raikou = { "SpSc", "DLPS" }
p.entei = { "SpSc", "DLPS" }
p.suicune = { "SpSc", "DLPS" }
p.larvitar = { "SpSc", "DLPS" }
p.pupitar = { "SpSc", "DLPS" }
p.tyranitar = { "SpSc", "DLPS" }
p.lugia = { "SpSc", "DLPS" }
p["ho-oh"] = { "SpSc", "DLPS" }
p.celebi = { "SpSc", "DLPS" }
p.treecko = { "SpSc", "DLPS" }
p.grovyle = { "SpSc", "DLPS" }
p.sceptile = { "SpSc", "DLPS" }
p.torchic = { "SpSc", "DLPS" }
p.combusken = { "SpSc", "DLPS" }
p.blaziken = { "SpSc", "DLPS" }
p.mudkip = { "SpSc", "DLPS" }
p.marshtomp = { "SpSc", "DLPS" }
p.swampert = { "SpSc", "DLPS" }
p.poochyena = { "DLPS" }
p.mightyena = { "DLPS" }
p.zigzagoon = { "SpSc", "DLPS" }
p.linoone = { "SpSc", "DLPS" }
p.wurmple = { "DLPS" }
p.silcoon = { "DLPS" }
p.beautifly = { "DLPS" }
p.cascoon = { "DLPS" }
p.dustox = { "DLPS" }
p.lotad = { "SpSc", "DLPS" }
p.lombre = { "SpSc", "DLPS" }
p.ludicolo = { "SpSc", "DLPS" }
p.seedot = { "SpSc", "DLPS" }
p.nuzleaf = { "SpSc", "DLPS" }
p.shiftry = { "SpSc", "DLPS" }
p.taillow = { "DLPS" }
p.swellow = { "DLPS" }
p.wingull = { "SpSc", "DLPS" }
p.pelipper = { "SpSc", "DLPS" }
p.ralts = { "SpSc", "DLPS" }
p.kirlia = { "SpSc", "DLPS" }
p.gardevoir = { "SpSc", "DLPS" }
p.surskit = { "DLPS" }
p.masquerain = { "DLPS" }
p.shroomish = { "DLPS" }
p.breloom = { "DLPS" }
p.slakoth = { "DLPS" }
p.vigoroth = { "DLPS" }
p.slaking = { "DLPS" }
p.nincada = { "SpSc", "DLPS" }
p.ninjask = { "SpSc", "DLPS" }
p.shedinja = { "SpSc", "DLPS" }
p.whismur = { "SpSc", "DLPS" }
p.loudred = { "SpSc", "DLPS" }
p.exploud = { "SpSc", "DLPS" }
p.makuhita = { "DLPS" }
p.hariyama = { "DLPS" }
p.azurill = { "SpSc", "DLPS" }
p.nosepass = { "DLPS" }
p.skitty = { "DLPS" }
p.delcatty = { "DLPS" }
p.sableye = { "SpSc", "DLPS" }
p.mawile = { "SpSc", "DLPS" }
p.aron = { "SpSc", "DLPS" }
p.lairon = { "SpSc", "DLPS" }
p.aggron = { "SpSc", "DLPS" }
p.meditite = { "DLPS" }
p.medicham = { "DLPS" }
p.electrike = { "SpSc", "DLPS" }
p.manectric = { "SpSc", "DLPS" }
p.plusle = { "DLPS" }
p.minun = { "DLPS" }
p.volbeat = { "DLPS" }
p.illumise = { "DLPS" }
p.roselia = { "SpSc", "DLPS" }
p.gulpin = { "DLPS" }
p.swalot = { "DLPS" }
p.carvanha = { "SpSc", "DLPS" }
p.sharpedo = { "SpSc", "DLPS" }
p.wailmer = { "SpSc", "DLPS" }
p.wailord = { "SpSc", "DLPS" }
p.numel = { "DLPS" }
p.camerupt = { "DLPS" }
p.torkoal = { "SpSc", "DLPS" }
p.spoink = { "DLPS" }
p.grumpig = { "DLPS" }
p.spinda = { "DLPS" }
p.trapinch = { "SpSc", "DLPS" }
p.vibrava = { "SpSc", "DLPS" }
p.flygon = { "SpSc", "DLPS" }
p.cacnea = { "DLPS" }
p.cacturne = { "DLPS" }
p.swablu = { "SpSc", "DLPS" }
p.altaria = { "SpSc", "DLPS" }
p.zangoose = { "DLPS" }
p.seviper = { "DLPS" }
p.lunatone = { "SpSc", "DLPS" }
p.solrock = { "SpSc", "DLPS" }
p.barboach = { "SpSc", "DLPS" }
p.whiscash = { "SpSc", "DLPS" }
p.corphish = { "SpSc", "DLPS" }
p.crawdaunt = { "SpSc", "DLPS" }
p.baltoy = { "SpSc", "DLPS" }
p.claydol = { "SpSc", "DLPS" }
p.lileep = { "SpSc", "DLPS" }
p.cradily = { "SpSc", "DLPS" }
p.anorith = { "SpSc", "DLPS" }
p.armaldo = { "SpSc", "DLPS" }
p.feebas = { "SpSc", "DLPS" }
p.milotic = { "SpSc", "DLPS" }
p.castform = { "DLPS" }
p.kecleon = { "DLPS" }
p.shuppet = { "DLPS" }
p.banette = { "DLPS" }
p.duskull = { "SpSc", "DLPS" }
p.dusclops = { "SpSc", "DLPS" }
p.tropius = { "DLPS" }
p.chimecho = { "DLPS" }
p.absol = { "SpSc", "DLPS" }
p.wynaut = { "SpSc", "DLPS" }
p.snorunt = { "SpSc", "DLPS" }
p.glalie = { "SpSc", "DLPS" }
p.spheal = { "SpSc", "DLPS" }
p.sealeo = { "SpSc", "DLPS" }
p.walrein = { "SpSc", "DLPS" }
p.clamperl = { "DLPS" }
p.huntail = { "DLPS" }
p.gorebyss = { "DLPS" }
p.relicanth = { "SpSc", "DLPS" }
p.luvdisc = { "DLPS" }
p.bagon = { "SpSc", "DLPS" }
p.shelgon = { "SpSc", "DLPS" }
p.salamence = { "SpSc", "DLPS" }
p.beldum = { "SpSc", "DLPS" }
p.metang = { "SpSc", "DLPS" }
p.metagross = { "SpSc", "DLPS" }
p.regirock = { "SpSc", "DLPS" }
p.regice = { "SpSc", "DLPS" }
p.registeel = { "SpSc", "DLPS" }
p.latias = { "SpSc", "DLPS" }
p.latios = { "SpSc", "DLPS" }
p.kyogre = { "SpSc", "DLPS" }
p.groudon = { "SpSc", "DLPS" }
p.rayquaza = { "SpSc", "DLPS" }
p.jirachi = { "SpSc", "DLPS" }
p.deoxys = { "DLPS" }
p.turtwig = { "DLPS" }
p.grotle = { "DLPS" }
p.torterra = { "DLPS" }
p.chimchar = { "DLPS" }
p.monferno = { "DLPS" }
p.infernape = { "DLPS" }
p.piplup = { "DLPS" }
p.prinplup = { "DLPS" }
p.empoleon = { "DLPS" }
p.starly = { "DLPS" }
p.staravia = { "DLPS" }
p.staraptor = { "DLPS" }
p.bidoof = { "DLPS" }
p.bibarel = { "DLPS" }
p.kricketot = { "DLPS" }
p.kricketune = { "DLPS" }
p.shinx = { "SpSc", "DLPS" }
p.luxio = { "SpSc", "DLPS" }
p.luxray = { "SpSc", "DLPS" }
p.budew = { "SpSc", "DLPS" }
p.roserade = { "SpSc", "DLPS" }
p.cranidos = { "DLPS" }
p.rampardos = { "DLPS" }
p.shieldon = { "DLPS" }
p.bastiodon = { "DLPS" }
p.burmy = { "DLPS" }
p.wormadam = { "DLPS" }
p.mothim = { "DLPS" }
p.combee = { "SpSc", "DLPS" }
p.vespiquen = { "SpSc", "DLPS" }
p.pachirisu = { "DLPS" }
p.buizel = { "DLPS" }
p.floatzel = { "DLPS" }
p.cherubi = { "SpSc", "DLPS" }
p.cherrim = { "SpSc", "DLPS" }
p.shellos = { "SpSc", "DLPS" }
p.gastrodon = { "SpSc", "DLPS" }
p.ambipom = { "DLPS" }
p.drifloon = { "SpSc", "DLPS" }
p.drifblim = { "SpSc", "DLPS" }
p.buneary = { "SpSc", "DLPS" }
p.lopunny = { "SpSc", "DLPS" }
p.mismagius = { "DLPS" }
p.honchkrow = { "DLPS" }
p.glameow = { "DLPS" }
p.purugly = { "DLPS" }
p.chingling = { "DLPS" }
p.stunky = { "SpSc", "DLPS" }
p.skuntank = { "SpSc", "DLPS" }
p.bronzor = { "SpSc", "DLPS" }
p.bronzong = { "SpSc", "DLPS" }
p.bonsly = { "SpSc", "DLPS" }
p["mime jr."] = { "SpSc", "DLPS" }
p.happiny = { "SpSc", "DLPS" }
p.chatot = { "DLPS" }
p.spiritomb = { "SpSc", "DLPS" }
p.gible = { "SpSc", "DLPS" }
p.gabite = { "SpSc", "DLPS" }
p.garchomp = { "SpSc", "DLPS" }
p.munchlax = { "SpSc", "DLPS" }
p.riolu = { "SpSc", "DLPS" }
p.lucario = { "SpSc", "DLPS" }
p.hippopotas = { "SpSc", "DLPS" }
p.hippowdon = { "SpSc", "DLPS" }
p.skorupi = { "SpSc", "DLPS" }
p.drapion = { "SpSc", "DLPS" }
p.croagunk = { "SpSc", "DLPS" }
p.toxicroak = { "SpSc", "DLPS" }
p.carnivine = { "DLPS" }
p.finneon = { "DLPS" }
p.lumineon = { "DLPS" }
p.mantyke = { "SpSc", "DLPS" }
p.snover = { "SpSc", "DLPS" }
p.abomasnow = { "SpSc", "DLPS" }
p.weavile = { "SpSc", "DLPS" }
p.magnezone = { "SpSc", "DLPS" }
p.lickilicky = { "SpSc", "DLPS" }
p.rhyperior = { "SpSc", "DLPS" }
p.tangrowth = { "SpSc", "DLPS" }
p.electivire = { "SpSc", "DLPS" }
p.magmortar = { "SpSc", "DLPS" }
p.togekiss = { "SpSc", "DLPS" }
p.yanmega = { "DLPS" }
p.leafeon = { "SpSc", "DLPS" }
p.glaceon = { "SpSc", "DLPS" }
p.gliscor = { "DLPS" }
p.mamoswine = { "SpSc", "DLPS" }
p["porygon-z"] = { "SpSc", "DLPS" }
p.gallade = { "SpSc", "DLPS" }
p.probopass = { "DLPS" }
p.dusknoir = { "SpSc", "DLPS" }
p.froslass = { "SpSc", "DLPS" }
p.rotom = { "SpSc", "DLPS" }
p.uxie = { "SpSc", "DLPS" }
p.mesprit = { "SpSc", "DLPS" }
p.azelf = { "SpSc", "DLPS" }
p.dialga = { "SpSc", "DLPS" }
p.palkia = { "SpSc", "DLPS" }
p.heatran = { "SpSc", "DLPS" }
p.regigigas = { "SpSc", "DLPS" }
p.giratina = { "SpSc", "DLPS" }
p.cresselia = { "SpSc", "DLPS" }
p.phione = { "DLPS" }
p.manaphy = { "DLPS" }
p.darkrai = { "DLPS" }
p.shaymin = { "DLPS" }
p.arceus = { "DLPS" }
p.victini = { "SpSc" }
p.snivy = {  }
p.servine = {  }
p.serperior = {  }
p.tepig = {  }
p.pignite = {  }
p.emboar = {  }
p.oshawott = {  }
p.dewott = {  }
p.samurott = {  }
p.patrat = {  }
p.watchog = {  }
p.lillipup = { "SpSc" }
p.herdier = { "SpSc" }
p.stoutland = { "SpSc" }
p.purrloin = { "SpSc" }
p.liepard = { "SpSc" }
p.pansage = {  }
p.simisage = {  }
p.pansear = {  }
p.simisear = {  }
p.panpour = {  }
p.simipour = {  }
p.munna = { "SpSc" }
p.musharna = { "SpSc" }
p.pidove = { "SpSc" }
p.tranquill = { "SpSc" }
p.unfezant = { "SpSc" }
p.blitzle = {  }
p.zebstrika = {  }
p.roggenrola = { "SpSc" }
p.boldore = { "SpSc" }
p.gigalith = { "SpSc" }
p.woobat = { "SpSc" }
p.swoobat = { "SpSc" }
p.drilbur = { "SpSc" }
p.excadrill = { "SpSc" }
p.audino = { "SpSc" }
p.timburr = { "SpSc" }
p.gurdurr = { "SpSc" }
p.conkeldurr = { "SpSc" }
p.tympole = { "SpSc" }
p.palpitoad = { "SpSc" }
p.seismitoad = { "SpSc" }
p.throh = { "SpSc" }
p.sawk = { "SpSc" }
p.sewaddle = {  }
p.swadloon = {  }
p.leavanny = {  }
p.venipede = { "SpSc" }
p.whirlipede = { "SpSc" }
p.scolipede = { "SpSc" }
p.cottonee = { "SpSc" }
p.whimsicott = { "SpSc" }
p.petilil = { "SpSc" }
p.lilligant = { "SpSc" }
p.basculin = { "SpSc" }
p.sandile = { "SpSc" }
p.krokorok = { "SpSc" }
p.krookodile = { "SpSc" }
p.darumaka = { "SpSc" }
p.darmanitan = { "SpSc" }
p.maractus = { "SpSc" }
p.dwebble = { "SpSc" }
p.crustle = { "SpSc" }
p.scraggy = { "SpSc" }
p.scrafty = { "SpSc" }
p.sigilyph = { "SpSc" }
p.yamask = { "SpSc" }
p.cofagrigus = { "SpSc" }
p.tirtouga = { "SpSc" }
p.carracosta = { "SpSc" }
p.archen = { "SpSc" }
p.archeops = { "SpSc" }
p.trubbish = { "SpSc" }
p.garbodor = { "SpSc" }
p.zorua = { "SpSc" }
p.zoroark = { "SpSc" }
p.minccino = { "SpSc" }
p.cinccino = { "SpSc" }
p.gothita = { "SpSc" }
p.gothorita = { "SpSc" }
p.gothitelle = { "SpSc" }
p.solosis = { "SpSc" }
p.duosion = { "SpSc" }
p.reuniclus = { "SpSc" }
p.ducklett = {  }
p.swanna = {  }
p.vanillite = { "SpSc" }
p.vanillish = { "SpSc" }
p.vanilluxe = { "SpSc" }
p.deerling = {  }
p.sawsbuck = {  }
p.emolga = { "SpSc" }
p.karrablast = { "SpSc" }
p.escavalier = { "SpSc" }
p.foongus = { "SpSc" }
p.amoonguss = { "SpSc" }
p.frillish = { "SpSc" }
p.jellicent = { "SpSc" }
p.alomomola = {  }
p.joltik = { "SpSc" }
p.galvantula = { "SpSc" }
p.ferroseed = { "SpSc" }
p.ferrothorn = { "SpSc" }
p.klink = { "SpSc" }
p.klang = { "SpSc" }
p.klinklang = { "SpSc" }
p.tynamo = {  }
p.eelektrik = {  }
p.eelektross = {  }
p.elgyem = { "SpSc" }
p.beheeyem = { "SpSc" }
p.litwick = { "SpSc" }
p.lampent = { "SpSc" }
p.chandelure = { "SpSc" }
p.axew = { "SpSc" }
p.fraxure = { "SpSc" }
p.haxorus = { "SpSc" }
p.cubchoo = { "SpSc" }
p.beartic = { "SpSc" }
p.cryogonal = { "SpSc" }
p.shelmet = { "SpSc" }
p.accelgor = { "SpSc" }
p.stunfisk = { "SpSc" }
p.mienfoo = { "SpSc" }
p.mienshao = { "SpSc" }
p.druddigon = { "SpSc" }
p.golett = { "SpSc" }
p.golurk = { "SpSc" }
p.pawniard = { "SpSc" }
p.bisharp = { "SpSc" }
p.bouffalant = { "SpSc" }
p.rufflet = { "SpSc" }
p.braviary = { "SpSc" }
p.vullaby = { "SpSc" }
p.mandibuzz = { "SpSc" }
p.heatmor = { "SpSc" }
p.durant = { "SpSc" }
p.deino = { "SpSc" }
p.zweilous = { "SpSc" }
p.hydreigon = { "SpSc" }
p.larvesta = { "SpSc" }
p.volcarona = { "SpSc" }
p.cobalion = { "SpSc" }
p.terrakion = { "SpSc" }
p.virizion = { "SpSc" }
p.tornadus = { "SpSc" }
p.thundurus = { "SpSc" }
p.reshiram = { "SpSc" }
p.zekrom = { "SpSc" }
p.landorus = { "SpSc" }
p.kyurem = { "SpSc" }
p.keldeo = { "SpSc" }
p.meloetta = {  }
p.genesect = { "SpSc" }
p.chespin = {  }
p.quilladin = {  }
p.chesnaught = {  }
p.fennekin = {  }
p.braixen = {  }
p.delphox = {  }
p.froakie = {  }
p.frogadier = {  }
p.greninja = {  }
p.bunnelby = { "SpSc" }
p.diggersby = { "SpSc" }
p.fletchling = { "SpSc" }
p.fletchinder = { "SpSc" }
p.talonflame = { "SpSc" }
p.scatterbug = {  }
p.spewpa = {  }
p.vivillon = {  }
p.litleo = {  }
p.pyroar = {  }
p["flabébé"] = {  }
p.floette = {  }
p.florges = {  }
p.skiddo = {  }
p.gogoat = {  }
p.pancham = { "SpSc" }
p.pangoro = { "SpSc" }
p.furfrou = {  }
p.espurr = { "SpSc" }
p.meowstic = { "SpSc" }
p.honedge = { "SpSc" }
p.doublade = { "SpSc" }
p.aegislash = { "SpSc" }
p.spritzee = { "SpSc" }
p.aromatisse = { "SpSc" }
p.swirlix = { "SpSc" }
p.slurpuff = { "SpSc" }
p.inkay = { "SpSc" }
p.malamar = { "SpSc" }
p.binacle = { "SpSc" }
p.barbaracle = { "SpSc" }
p.skrelp = { "SpSc" }
p.dragalge = { "SpSc" }
p.clauncher = { "SpSc" }
p.clawitzer = { "SpSc" }
p.helioptile = { "SpSc" }
p.heliolisk = { "SpSc" }
p.tyrunt = { "SpSc" }
p.tyrantrum = { "SpSc" }
p.amaura = { "SpSc" }
p.aurorus = { "SpSc" }
p.sylveon = { "SpSc" }
p.hawlucha = { "SpSc" }
p.dedenne = { "SpSc" }
p.carbink = { "SpSc" }
p.goomy = { "SpSc" }
p.sliggoo = { "SpSc" }
p.goodra = { "SpSc" }
p.klefki = { "SpSc" }
p.phantump = { "SpSc" }
p.trevenant = { "SpSc" }
p.pumpkaboo = { "SpSc" }
p.gourgeist = { "SpSc" }
p.bergmite = { "SpSc" }
p.avalugg = { "SpSc" }
p.noibat = { "SpSc" }
p.noivern = { "SpSc" }
p.xerneas = { "SpSc" }
p.yveltal = { "SpSc" }
p.zygarde = { "SpSc" }
p.diancie = { "SpSc" }
p.hoopa = {  }
p.volcanion = { "SpSc" }
p.rowlet = { "SpSc" }
p.dartrix = { "SpSc" }
p.decidueye = { "SpSc" }
p.litten = { "SpSc" }
p.torracat = { "SpSc" }
p.incineroar = { "SpSc" }
p.popplio = { "SpSc" }
p.brionne = { "SpSc" }
p.primarina = { "SpSc" }
p.pikipek = {  }
p.trumbeak = {  }
p.toucannon = {  }
p.yungoos = {  }
p.gumshoos = {  }
p.grubbin = { "SpSc" }
p.charjabug = { "SpSc" }
p.vikavolt = { "SpSc" }
p.crabrawler = {  }
p.crabominable = {  }
p.oricorio = {  }
p.cutiefly = { "SpSc" }
p.ribombee = { "SpSc" }
p.rockruff = { "SpSc" }
p.lycanroc = { "SpSc" }
p.wishiwashi = { "SpSc" }
p.mareanie = { "SpSc" }
p.toxapex = { "SpSc" }
p.mudbray = { "SpSc" }
p.mudsdale = { "SpSc" }
p.dewpider = { "SpSc" }
p.araquanid = { "SpSc" }
p.fomantis = { "SpSc" }
p.lurantis = { "SpSc" }
p.morelull = { "SpSc" }
p.shiinotic = { "SpSc" }
p.salandit = { "SpSc" }
p.salazzle = { "SpSc" }
p.stufful = { "SpSc" }
p.bewear = { "SpSc" }
p.bounsweet = { "SpSc" }
p.steenee = { "SpSc" }
p.tsareena = { "SpSc" }
p.comfey = { "SpSc" }
p.oranguru = { "SpSc" }
p.passimian = { "SpSc" }
p.wimpod = { "SpSc" }
p.golisopod = { "SpSc" }
p.sandygast = { "SpSc" }
p.palossand = { "SpSc" }
p.pyukumuku = { "SpSc" }
p["tipo zero"] = { "SpSc" }
p.silvally = { "SpSc" }
p.minior = {  }
p.komala = {  }
p.turtonator = { "SpSc" }
p.togedemaru = { "SpSc" }
p.mimikyu = { "SpSc" }
p.bruxish = {  }
p.drampa = { "SpSc" }
p.dhelmise = { "SpSc" }
p["jangmo-o"] = { "SpSc" }
p["hakamo-o"] = { "SpSc" }
p["kommo-o"] = { "SpSc" }
p["tapu koko"] = { "SpSc" }
p["tapu lele"] = { "SpSc" }
p["tapu bulu"] = { "SpSc" }
p["tapu fini"] = { "SpSc" }
p.cosmog = { "SpSc" }
p.cosmoem = { "SpSc" }
p.solgaleo = { "SpSc" }
p.lunala = { "SpSc" }
p.nihilego = { "SpSc" }
p.buzzwole = { "SpSc" }
p.pheromosa = { "SpSc" }
p.xurkitree = { "SpSc" }
p.celesteela = { "SpSc" }
p.kartana = { "SpSc" }
p.guzzlord = { "SpSc" }
p.necrozma = { "SpSc" }
p.magearna = { "SpSc" }
p.marshadow = { "SpSc" }
p.poipole = { "SpSc" }
p.naganadel = { "SpSc" }
p.stakataka = { "SpSc" }
p.blacephalon = { "SpSc" }
p.zeraora = { "SpSc" }
p.meltan = { "SpSc" }
p.melmetal = { "SpSc" }
p.grookey = { "SpSc" }
p.thwackey = { "SpSc" }
p.rillaboom = { "SpSc" }
p.scorbunny = { "SpSc" }
p.raboot = { "SpSc" }
p.cinderace = { "SpSc" }
p.sobble = { "SpSc" }
p.drizzile = { "SpSc" }
p.inteleon = { "SpSc" }
p.skwovet = { "SpSc" }
p.greedent = { "SpSc" }
p.rookidee = { "SpSc" }
p.corvisquire = { "SpSc" }
p.corviknight = { "SpSc" }
p.blipbug = { "SpSc" }
p.dottler = { "SpSc" }
p.orbeetle = { "SpSc" }
p.nickit = { "SpSc" }
p.thievul = { "SpSc" }
p.gossifleur = { "SpSc" }
p.eldegoss = { "SpSc" }
p.wooloo = { "SpSc" }
p.dubwool = { "SpSc" }
p.chewtle = { "SpSc" }
p.drednaw = { "SpSc" }
p.yamper = { "SpSc" }
p.boltund = { "SpSc" }
p.rolycoly = { "SpSc" }
p.carkol = { "SpSc" }
p.coalossal = { "SpSc" }
p.applin = { "SpSc" }
p.flapple = { "SpSc" }
p.appletun = { "SpSc" }
p.silicobra = { "SpSc" }
p.sandaconda = { "SpSc" }
p.cramorant = { "SpSc" }
p.arrokuda = { "SpSc" }
p.barraskewda = { "SpSc" }
p.toxel = { "SpSc" }
p.toxtricity = { "SpSc" }
p.sizzlipede = { "SpSc" }
p.centiskorch = { "SpSc" }
p.clobbopus = { "SpSc" }
p.grapploct = { "SpSc" }
p.sinistea = { "SpSc" }
p.polteageist = { "SpSc" }
p.hatenna = { "SpSc" }
p.hattrem = { "SpSc" }
p.hatterene = { "SpSc" }
p.impidimp = { "SpSc" }
p.morgrem = { "SpSc" }
p.grimmsnarl = { "SpSc" }
p.obstagoon = { "SpSc" }
p.perrserker = { "SpSc" }
p.cursola = { "SpSc" }
p["sirfetch'd"] = { "SpSc" }
p["mr. rime"] = { "SpSc" }
p.runerigus = { "SpSc" }
p.milcery = { "SpSc" }
p.alcremie = { "SpSc" }
p.falinks = { "SpSc" }
p.pincurchin = { "SpSc" }
p.snom = { "SpSc" }
p.frosmoth = { "SpSc" }
p.stonjourner = { "SpSc" }
p.eiscue = { "SpSc" }
p.indeedee = { "SpSc" }
p.morpeko = { "SpSc" }
p.cufant = { "SpSc" }
p.copperajah = { "SpSc" }
p.dracozolt = { "SpSc" }
p.arctozolt = { "SpSc" }
p.dracovish = { "SpSc" }
p.arctovish = { "SpSc" }
p.duraludon = { "SpSc" }
p.dreepy = { "SpSc" }
p.drakloak = { "SpSc" }
p.dragapult = { "SpSc" }
p.zacian = { "SpSc" }
p.zamazenta = { "SpSc" }
p.eternatus = { "SpSc" }
p.kubfu = { "SpSc" }
p.urshifu = { "SpSc" }
p.zarude = { "SpSc" }
p.regieleki = { "SpSc" }
p.regidrago = { "SpSc" }
p.glastrier = { "SpSc" }
p.spectrier = { "SpSc" }
p.calyrex = { "SpSc" }

p.rattataA = { }
p['019A'] = p.rattataA
p.raticateA = { }
p['020A'] = p.raticateA
p.raichuA = { "SpSc" }
p['026A'] = p.raichuA
p.sandshrewA = { "SpSc" }
p['027A'] = p.sandshrewA
p.sandslashA = { "SpSc" }
p['028A'] = p.sandslashA
p.vulpixA = { "SpSc" }
p['037A'] = p.vulpixA
p.ninetalesA = { "SpSc" }
p['038A'] = p.ninetalesA
p.diglettA = { "SpSc" }
p['050A'] = p.diglettA
p.dugtrioA = { "SpSc" }
p['051A'] = p.dugtrioA
p.meowthA = { "SpSc" }
p['052A'] = p.meowthA
p.meowthG = { "SpSc" }
p['052G'] = p.meowthG
p.persianA = { "SpSc" }
p['053A'] = p.persianA
p.growlitheH = {}
p['058H'] = p.growlitheH
p.geodudeA = {}
p['074A'] = p.geodudeA
p.gravelerA = {}
p['075A'] = p.gravelerA
p.golemA = {}
p['076A'] = p.golemA
p.ponytaG = { "SpSc" }
p['077G'] = p.ponytaG
p.rapidashG = { "SpSc" }
p['078G'] = p.rapidashG
p.slowpokeG = { "SpSc" }
p['079G'] = p.slowpokeG
p.slowbroG = { "SpSc" }
p['080G'] = p.slowbroG
p["farfetch'dG"] = { "SpSc" }
p['083G'] = p["farfetch'dG"]
p.grimerA = {}
p['088A'] = p.grimerA
p.mukA = {}
p['089A'] = p.mukA
p.exeggutorA = { "SpSc" }
p['103A'] = p.exeggutorA
p.marowakA = { "SpSc" }
p['105A'] = p.marowakA
p.weezingG = { "SpSc" }
p['110G'] = p.weezingG
p['mr. mimeG'] = { "SpSc" }
p['122G'] = p['mr. mimeG']
p.articunoG = { "SpSc" }
p['144G'] = p.articunoG
p.zapdosG = { "SpSc" }
p['145G'] = p.zapdosG
p.moltresG = { "SpSc" }
p['146G'] = p.moltresG
p.slowkingG = { "SpSc" }
p['199G'] = p.slowkingG
p.corsolaG = { "SpSc" }
p['222G'] = p.corsolaG
p.zigzagoonG = { "SpSc" }
p['263G'] = p.zigzagoonG
p.linooneG = { "SpSc" }
p['264G'] = p.linooneG
p.castformS = { "DLPS" }
p['351S'] = p.castformS
p.castformP = { "DLPS" }
p['351P'] = p.castformP
p.castformN = { "DLPS" }
p['351N'] = p.castformN
p.wormadamSa = { "DLPS" }
p['413Sa'] = p.wormadamSa
p.wormadamSc = { "DLPS" }
p['413Sc'] = p.wormadamSc
p.rotomC = { "SpSc", "DLPS" }
p['479C'] = p.rotomC
p.rotomL = { "SpSc", "DLPS" }
p['479L'] = p.rotomL
p.rotomG = { "SpSc", "DLPS" }
p['479G'] = p.rotomG
p.rotomV = { "SpSc", "DLPS" }
p['479V'] = p.rotomV
p.rotomT = { "SpSc", "DLPS" }
p['479T'] = p.rotomT
p.shayminC = { "DLPS" }
p['492C'] = p.shayminC
-- Arceus
p.darumakaG = { "SpSc" }
p['554G'] = p.darumakaG
p.darmanitanZ = { "SpSc" }
p['555Z'] = p.darmanitanZ
p.darmanitanG = { "SpSc" }
p['555G'] = p.darmanitanG
p.darmanitanGZ = { "SpSc" }
p['555GZ'] = p.darmanitanGZ
p.yamaskG = { "SpSc" }
p['562G'] = p.yamaskG
p.stunfiskG = { "SpSc" }
p['618G'] = p.stunfiskG
p.braviaryH = { }
p['628H'] = p.braviaryH
p.meloettaD = { }
p['648D'] = p.meloettaD
p.hoopaL = { }
p['720L'] = p.hoopaL
p.oricorioC = {}
p['741C'] = p.oricorioC
p.oricorioH = { }
p['741H'] = p.oricorioH
p.oricorioB = { }
p['741B'] = p.oricorioB
-- p.silvallyL = {name = 'Silvally', ndex = 773, type1 = 'lotta', type2 = 'lotta'}
-- p['773L'] = p.silvallyL
-- p.silvallyVo = {name = 'Silvally', ndex = 773, type1 = 'volante', type2 = 'volante'}
-- p['773Vo'] = p.silvallyVo
-- p.silvallyVe = {name = 'Silvally', ndex = 773, type1 = 'veleno', type2 = 'veleno'}
-- p['773Ve'] = p.silvallyVe
-- p.silvallyT = {name = 'Silvally', ndex = 773, type1 = 'terra', type2 = 'terra'}
-- p['773T'] = p.silvallyT
-- p.silvallyR = {name = 'Silvally', ndex = 773, type1 = 'roccia', type2 = 'roccia'}
-- p['773R'] = p.silvallyR
-- p.silvallyC = {name = 'Silvally', ndex = 773, type1 = 'coleottero', type2 = 'coleottero'}
-- p['773C'] = p.silvallyC
-- p.silvallyS = {name = 'Silvally', ndex = 773, type1 = 'spettro', type2 = 'spettro'}
-- p['773S'] = p.silvallyS
-- p.silvallyAi = {name = 'Silvally', ndex = 773, type1 = 'acciaio', type2 = 'acciaio'}
-- p['773Ai'] = p.silvallyAi
-- p.silvallyFu = {name = 'Silvally', ndex = 773, type1 = 'fuoco', type2 = 'fuoco'}
-- p['773Fu'] = p.silvallyFu
-- p.silvallyAq = {name = 'Silvally', ndex = 773, type1 = 'acqua', type2 = 'acqua'}
-- p['773Aq'] = p.silvallyAq
-- p.silvallyEr = {name = 'Silvally', ndex = 773, type1 = 'erba', type2 = 'erba'}
-- p['773Er'] = p.silvallyEr
-- p.silvallyEl = {name = 'Silvally', ndex = 773, type1 = 'elettro', type2 = 'elettro'}
-- p['773El'] = p.silvallyEl
-- p.silvallyP = {name = 'Silvally', ndex = 773, type1 = 'psico', type2 = 'psico'}
-- p['773P'] = p.silvallyP
-- p.silvallyG = {name = 'Silvally', ndex = 773, type1 = 'ghiaccio', type2 = 'ghiaccio'}
-- p['773G'] = p.silvallyG
-- p.silvallyD = {name = 'Silvally', ndex = 773, type1 = 'drago', type2 = 'drago'}
-- p['773D'] = p.silvallyD
-- p.silvallyB = {name = 'Silvally', ndex = 773, type1 = 'buio', type2 = 'buio'}
-- p['773B'] = p.silvallyB
-- p.silvallyFo = {name = 'Silvally', ndex = 773, type1 = 'folletto', type2 = 'folletto'}
-- p['773Fo'] = p.silvallyFo
p.necrozmaV = { "SpSc" }
p['800V'] = p.necrozmaV
p.necrozmaA = { "SpSc" }
p['800A'] = p.necrozmaA
p.necrozmaU = { "SpSc" }
p['800U'] = p.necrozmaU
p.urshifuP = { "SpSc" }
p['892P'] = p.urshifuP
p.calyrexG = { "SpSc" }
p['898G'] = p.calyrexG
p.calyrexS = { "SpSc" }
p['898S'] = p.calyrexS

-- Gli alias per le altre forme alternative rilevanti

p.deoxysA, p.deoxysD, p.deoxysV = p.deoxys, p.deoxys, p.deoxys
p['386A'], p['386D'], p['386V'] = p.deoxysA, p.deoxysD, p.deoxysV
p.giratinaO = p.giratina
p['487O'] = p.giratinaO
p.basculinB  = p.basculin
p['550B'] = p.basculinB
p.tornadusT = p.tornadus
p.thundurusT = p.thundurus
p.landorusT = p.landorus
p['641T'], p['642T'], p['645T'] = p.tornadusT, p.thundurusT, p.landorusT
p.kyuremN, p.kyuremB = p.kyurem, p.kyurem
p['646N'], p['646B'] = p.kyuremN, p.kyuremB
-- p.greninjaA, p['658A'] = p.greninja, p.greninja
p.meowsticF = p.meowstic
p['678F'] = p.meowsticF
p.aegislashS = p.aegislash
p['681S'] = p.aegislashS
p.pumpkabooS, p.pumpkabooL, p.pumpkabooXL = p.pumpkaboo, p.pumpkaboo, p.pumpkaboo
p['710S'], p['710L'], p['710XL'] = p.pumpkabooS, p.pumpkabooL, p.pumpkabooXL
p.gourgeistS, p.gourgeistL, p.gourgeistXL = p.gourgeist, p.gourgeist, p.gourgeist
p['711S'], p['711L'], p['711XL'] = p.gourgeistS, p.gourgeistL, p.gourgeistXL
p.zygardeD, p.zygardeP = p.zygarde, p.zygarde
p['718D'], p['718P'] = p.zygardeD, p.zygardeP
p.lycanrocN, p.lycanrocC = p.lycanroc, p.lycanroc
p['745N'], p['745C'] = p.lycanrocN, p.lycanrocC
p.wishiwashiB = p.wishiwashi
p['746B'] = p.wishiwashiB
p.miniorR = p.minior
p['774R'] = p.miniorR
-- p.cramorantT, p['845T'], p.cramorantI, p['845I'] =
--     p.cramorant, p.cramorant, p.cramorant, p.cramorant
p.toxtricityB = p.toxtricity
p['849B'] = p.toxtricityB
p.eiscueL = p.eiscue
p['875L'] = p.eiscueL
p.indeedeeF = p.indeedee
p['876F'] = p.indeedeeF
p.morpekoV = p.morpeko
p['877V'] = p.morpekoV
p.zacianR = p.zacian
p['888R'] = p.zacianR
p.zamazentaR = p.zamazenta
p['889R'] = p.zamazentaR
p.eternatusD = p.eternatus
p['890D'] = p.eternatusD

-- Mega e Gigamax, todo

-- p.charizardMX = { }
-- p['006MX'] = p.charizardMX
-- p.pinsirM = { }
-- p['127M'] = p.pinsirM
-- p.gyaradosM = { }
-- p['130M'] = p.gyaradosM
-- p.mewtwoMX = { }
-- p['150MX'] = p.mewtwoMX
-- p.ampharosM = { }
-- p['181M'] = p.ampharosM
-- p.sceptileM = { }
-- p['254M'] = p.sceptileM
-- -- It's not an alias because Gardevoir changed its type in sixth gen
-- p.gardevoirM = { }
-- p['282M'] = p.gardevoirM
-- p.mawileM = { }
-- p['303M'] = p.mawileM
-- p.aggronM = { }
-- p['306M'] = p.aggronM
-- p.altariaM = { }
-- p['334M'] = p.altariaM
-- p.groudonA = { }
-- p['383A'] = p.groudonA
-- p.lopunnyM = { }
-- p['428M'] = p.lopunnyM
-- p.audinoM = { }
-- p['531M'] = p.audinoM
-- p.venusaurM, p['003M'] = p.venusaur, p.venusaur
-- t.charizardMY, p['006MY'] = t.charizard, t.charizard
-- t.blastoiseM, p['009M'] = t.blastoise, t.blastoise
-- t.beedrillM, p['015M'] = t.beedrill, t.beedrill
-- t.pidgeotM, p['018M'] = t.pidgeot, t.pidgeot
-- t.alakazamM, p['065M'] = t.alakazam, t.alakazam
-- t.slowbroM, p['080M'] = t.slowbro, t.slowbro
-- t.gengarM, p['094M'] = t.gengar, t.gengar
-- t.kangaskhanM, p['115M'] = t.kangaskhan, t.kangaskhan
-- t.aerodactylM, p['142M'] = t.aerodactyl, t.aerodactyl
-- t.mewtwoMY, p['150MY'] = t.mewtwo, t.mewtwo
-- t.steelixM, p['208M'] = t.steelix, t.steelix
-- t.scizorM, p['212M'] = t.scizor, t.scizor
-- t.heracrossM, p['214M'] = t.heracross, t.heracross
-- t.houndoomM, p['229M'] = t.houndoom, t.houndoom
-- t.tyranitarM, p['248M'] = t.tyranitar, t.tyranitar
-- t.blazikenM, p['257M'] = t.blaziken, t.blaziken
-- t.swampertM, p['260M'] = t.swampert, t.swampert
-- t.sableyeM, p['302M'] = t.sableye, t.sableye
-- t.medichamM, p['308M'] = t.medicham, t.medicham
-- t.manectricM, p['310M'] = t.manectric, t.manectric
-- t.sharpedoM, p['319M'] = t.sharpedo, t.sharpedo
-- t.cameruptM, p['323M'] = t.camerupt, t.camerupt
-- t.banetteM, p['354M'] = t.banette, t.banette
-- t.absolM, p['359M'] = t.absol, t.absol
-- t.glalieM, p['362M'] = t.glalie, t.glalie
-- t.salamenceM, p['373M'] = t.salamence, t.salamence
-- t.metagrossM, p['376M'] = t.metagross, t.metagross
-- t.latiasM, p['380M'] = t.latias, t.latias
-- t.latiosM, p['381M'] = t.latios, t.latios
-- t.rayquazaM, p['384M'] = t.rayquaza, t.rayquaza
-- t.kyogreA, p['382A'] = t.kyogre, t.kyogre
-- t.garchompM, p['445M'] = t.garchomp, t.garchomp
-- t.lucarioM, p['448M'] = t.lucario, t.lucario
-- t.abomasnowM, p['460M'] = t.abomasnow, t.abomasnow
-- t.galladeM, p['475M'] = t.gallade, t.gallade
-- t.diancieM, p['719M'] = t.diancie, t.diancie
-- t.venusaurGi, p['003Gi'] = t.venusaur, t.venusaur
-- t.charizardGi, p['006Gi'] = t.charizard, t.charizard
-- t.blastoiseGi, p['009Gi'] = t.blastoise, t.blastoise
-- t.butterfreeGi, p['012Gi'] = t.butterfree, t.butterfree
-- t.pikachuGi, p['025Gi'] = t.pikachu, t.pikachu
-- t.meowthGi, p['052Gi'] = t.meowth, t.meowth
-- t.machampGi, p['068Gi'] = t.machamp, t.machamp
-- t.gengarGi, p['094Gi'] = t.gengar, t.gengar
-- t.kinglerGi, p['099Gi'] = t.kingler, t.kingler
-- t.laprasGi, p['131Gi'] = t.lapras, t.lapras
-- t.eeveeGi, p['133Gi'] = t.eevee, t.eevee
-- t.snorlaxGi, p['143Gi'] = t.snorlax, t.snorlax
-- t.garbodorGi, p['569Gi'] = t.garbodor, t.garbodor
-- t.melmetalGi, p['809Gi'] = t.melmetal, t.melmetal
-- t.rillaboomGi, p['812Gi'] = t.rillaboom, t.rillaboom
-- t.cinderaceGi, p['815Gi'] = t.cinderace, t.cinderace
-- t.inteleonGi, p['818Gi'] = t.inteleon, t.inteleon
-- t.corviknightGi, p['823Gi'] = t.corviknight, t.corviknight
-- t.orbeetleGi, p['826Gi'] = t.orbeetle, t.orbeetle
-- t.drednawGi, p['834Gi'] = t.drednaw, t.drednaw
-- t.coalossalGi, p['839Gi'] = t.coalossal, t.coalossal
-- t.flappleGi, p['841Gi'] = t.flapple, t.flapple
-- t.appletunGi, p['842Gi'] = t.appletun, t.appletun
-- t.sandacondaGi, p['844Gi'] = t.sandaconda, t.sandaconda
-- t.toxtricityGi, p['849Gi'] = t.toxtricity, t.toxtricity
-- t.centiskorchGi, p['851Gi'] = t.centiskorch, t.centiskorch
-- t.hattereneGi, p['858Gi'] = t.hatterene, t.hatterene
-- t.grimmsnarlGi, p['861Gi'] = t.grimmsnarl, t.grimmsnarl
-- t.alcremieGi, p['869Gi'] = t.alcremie, t.alcremie
-- t.copperajahGi, p['879Gi'] = t.copperajah, t.copperajah
-- t.duraludonGi, p['884Gi'] = t.duraludon, t.duraludon
-- t.urshifuGi, p['892Gi'] = t.urshifu, t.urshifu
-- t.urshifuPGi, p['892PGi'] = t.urshifuP, t.urshifuP

return p
