#!/bin/bash

# This script is meant to download
# ndex ranges generated by
# lua/generate-ndex-range.lua

# All the arguments from the third onwards
# are directly passed to get-wiki-file.sh,
# including named parameters and flags

# Arguments:
#	- $1: File containing the generated filenames.
#	- $2: Destination path
#	- $3+: get-wiki-file.sh parameters

SOURCE="$1"
DEST="$2"
shift 2

OLD_IFS=$IFS
IFS=$'\n'

while read -r FILENAME; do
	IFS=$OLD_IFS

    bash get-wiki-file.sh "$@" "$FILENAME" "$DEST"

    OLD_IFS=$IFS
	IFS=$'\n'
done < "$SOURCE"
