import argparse, re, sys, os, os.path, json
import pywikibot

"""
This script generates a list containing ndexes of all Pokémon, including their
alt forms, and writes it to a text file. Arguments are already populated, ensure
that they point to correct files locations.
"""


# main function
def main():
    # parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("--pokesfile", default="data/wiki-util-data/poke-names.json")  # fmt: skip
    parser.add_argument("--formsfile", default="data/wiki-util-data/forms-availability.json")  # fmt: skip
    args = parser.parse_args()
    # read input files
    with open(args.pokesfile, "r") as file:
        pokes_data = json.load(file)
    with open(args.formsfile, "r") as file:
        forms_data = json.load(file)
    # find path of script and build path of output file
    script_path = os.path.realpath(__file__)
    script_name = os.path.basename(script_path)
    script_dir = os.path.dirname(script_path)
    repo_dir = os.path.dirname(script_dir)
    output_path = os.path.join(repo_dir, "shared", "all-pokeabbrs.txt")
    output_txt = f"# This file is automatically generated using {script_name}\n"
    # extract ndexes and forms from input files
    # ndexes = [p["ndex"] for p in pokes_data]
    forms = [key for key in forms_data]
    # loop over all ndexes to build content of output file
    for p in pokes_data:
        ndex = p["ndex"]
        poke = p["poke"]
        output_txt += f"{poke}\n"
        ndexabbrs = [form for form in forms if re.search(r"\b" + str(ndex) + r"[A-z]+", form)]  # fmt: skip
        for ndexabbr in ndexabbrs:
            abbr = re.sub(r"\d", "", ndexabbr)
            pokeabbr = f"{poke}{abbr}"
            output_txt += f"{pokeabbr}\n"
    # write generated file
    print(f"Writing output file {output_path}")
    with open(output_path, "w") as file:
        file.write(output_txt)


# invoke main function
if __name__ == "__main__":
    main()
